POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
  "fName": "Eduard",
  "lName": "tiutiunnyk",
  "email": "ediktyutyunnik@gmail.com",
  "password": "5416",
  "age": 26,
  "isMale": true
}